<a href="https://colab.research.google.com/github/Yehor-Makeiev/HW10/blob/main/HW3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
import numpy as np

def linear_regression(x: np.array, w: np.array):
    return np.dot(x, w)

In [13]:
def cost(X: np.array, w: np.array, y: np.array):
    return np.dot(X.T, (np.dot(X, w) - y)) / len(y)

In [14]:
def gradient_descent_step(X, w, y, a):
    return w - (cost(X, w, y) * a)

In [15]:
#preparing data
df = pd.read_csv("Housing.csv")
y = df["price"].to_numpy()
X = df[["area", "bathrooms", "bedrooms"]].to_numpy()
ones = np.ones(len(y))[:, np.newaxis]
X = np.concatenate((np.ones(len(y), dtype=int)[:, np.newaxis], X), axis=1)
X = X.astype(float)
w = np.random.randn(4)
a = 1

In [16]:
#normalizing
n = X.mean(axis=0)
s = X.max(axis=0) - X.min(axis=0)
for i in range(1, 4):
    new_x = (X[:, i] - n[i]) / s[i]
    X[:, i] = new_x
print(X)

[[ 1.          0.15597654  0.23792049  0.20697248]
 [ 1.          0.26181847  0.90458716  0.20697248]
 [ 1.          0.33054699  0.23792049  0.00697248]
 ...
 [ 1.         -0.10519184 -0.09541284 -0.19302752]
 [ 1.         -0.15398909 -0.09541284  0.00697248]
 [ 1.         -0.08938428 -0.09541284  0.00697248]]


In [17]:
#testing
print(linear_regression(X[0], w))
print(cost(X, w, y))
print(gradient_descent_step(X, w, y, a))

0.7772660233723304
[-4766729.03287922  -149256.60508665  -161838.89367142  -101003.60919907]
[4766729.24770642  149258.37152005  161840.69866763  101002.9205619 ]


In [20]:
#learning
w_prev = [0, 0, 0, 0]
while not(w==w_prev).all():
    w_prev = w
    w = gradient_descent_step(X, w, y, a)
print(w)

[4766729.24770642 5510998.06466328 4158148.49337298 2034100.16884592]


In [21]:
#finding the weights analiticaly
w_an = np.dot(np.dot(np.linalg.inv(np.dot(X.T, X)), X.T), y)
print(w_an)
# [4766729.24770642 5510998.06466326 4158148.49337299 2034100.1688459]

[4766729.24770642 5510998.06466325 4158148.493373   2034100.1688459 ]


In [22]:
#comapring
diff = (w - w_an) / w * 100
print(diff)
# [ 0.00000000e+00  1.85892795e-13 -2.68770365e-13  8.01245942e-13]
# I think this is acurate enough

[ 0.00000000e+00  5.40779039e-13 -4.25553078e-13  9.95834242e-13]
